FROM ghcr.io/espressosystems/nitro-espresso-integration/nitro-node-dev:latest

COPY ./config /config/
COPY ./l1keystore /l1keystore/

EXPOSE 8547
EXPOSE 8548

ENTRYPOINT ["/usr/local/bin/nitro"]
CMD ["--conf.file", "/config/poster_config.json"]