services:
  postgres:
    image: postgres:13.6
    restart: always
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:7432:5432"

  redis:
    image: redis:6.2.6
    ports:
      - "127.0.0.1:6379:6379"

  geth:
    image: ethereum/client-go:v1.10.23
    ports:
      - "127.0.0.1:8545:8545"
      - "127.0.0.1:8551:8551"
      - "127.0.0.1:8546:8546"
      - "127.0.0.1:30303:30303"
    volumes:
      - "l1data:/datadir"
      - "l1keystore:/keystore"
      - "config:/config"
    command:
      - --keystore=/keystore
      - --http
      - --datadir=/datadir
      - --http.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.port=8551
      - --authrpc.addr=0.0.0.0
      - --http.vhosts=*
      - --http.api=engine,personal,eth,net,web3
      - --http.corsdomain=*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.api=personal,eth,net,web3,debug,txpool
      - --allow-insecure-unlock
      - --unlock=0x3f1Eae7D46d88F08fc2F8ed27FCb2AB183EB2d0E
      - --password=/datadir/passphrase
      - --authrpc.jwtsecret=/config/jwt.hex
      - --nodiscover
      - --syncmode=full
      - --dev
      - --dev.period=1
      - --mine
      - --miner.etherbase=0x3f1Eae7D46d88F08fc2F8ed27FCb2AB183EB2d0E
      - --gcmode=archive

  sequencer:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    entrypoint: /usr/local/bin/nitro
    ports:
      - "127.0.0.1:8547:8547"
      - "127.0.0.1:8548:8548"
      - "127.0.0.1:9642:9642"
    volumes:
      - "seqdata:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/sequencer_config.json --node.feed.output.enable --node.feed.output.port 9642  --http.api net,web3,eth,txpool,debug --node.seq-coordinator.my-url  ws://sequencer:8548 --graphql.enable --graphql.vhosts * --graphql.corsdomain *
    depends_on:
      - geth

  # Reads from sequencer feed, forwards transactions to sequencer
  full-node:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    ports:
      - "127.0.0.1:8947:8547"
      - "127.0.0.1:8948:8548"
    entrypoint: /usr/local/bin/nitro
    volumes:
      - "config:/config"
      - "l1keystore:/home/user/l1keystore"
    # use the sequencer_config.json but override the sequencer settings and the forwarding settings.
    command: --conf.file /config/sequencer_config.json --node.sequencer=false --node.batch-poster.enable=false --execution.sequencer.enable=false --execution.forwarding-target http://sequencer:8547 --node.delayed-sequencer.enable=false --node.feed.input.url ws://sequencer:9642 --http.port 8547 --http.api net,web3,arb,debug,net,eth --ws.port 8548
    depends_on:
      - geth
      - sequencer

  poster:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    entrypoint: /usr/local/bin/nitro
    ports:
      - "127.0.0.1:8147:8547"
      - "127.0.0.1:8148:8548"
    volumes:
      - "poster-data:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/poster_config.json
    depends_on:
      - geth
      - redis

  validator:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    entrypoint: /usr/local/bin/nitro
    ports:
      - "127.0.0.1:8247:8547"
      - "127.0.0.1:8248:8548"
    volumes:
      - "validator-data:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/validator_config.json --http.port 8547 --http.api net,web3,arb,debug,net,eth --ws.port 8548
    depends_on:
      - sequencer
      - validation_node

  validation_node:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    entrypoint: /usr/local/bin/nitro-val
    ports:
      - "127.0.0.1:8949:8549"
    volumes:
      - "config:/config"
    command: --conf.file /config/validation_node_config.json

  scripts:
    build: scripts/
    volumes:
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"

  rollupcreator:
    depends_on:
      - geth
      - sequencer
    pid: host
    build:
      context: rollupcreator/
      args:
        NITRO_CONTRACTS_REPO: ${NITRO_CONTRACTS_REPO:-}
        NITRO_CONTRACTS_BRANCH: ${NITRO_CONTRACTS_BRANCH:-}
    volumes:
      - "config:/config"
      - /var/run/docker.sock:/var/run/docker.sock

  espresso-dev-node:
    # TODO: revert to `:main` tag once we are compatible with the marketplace builder
    image: ghcr.io/espressosystems/espresso-sequencer/espresso-dev-node:20240919-dev-node-legacy-builder
    ports:
      - "$ESPRESSO_SEQUENCER_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
      - "$ESPRESSO_BUILDER_PORT:$ESPRESSO_BUILDER_PORT"
      - "$ESPRESSO_DEV_NODE_PORT:$ESPRESSO_DEV_NODE_PORT"
    environment:
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_DEPLOYER_ACCOUNT_INDEX
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_BUILDER_PORT
      - ESPRESSO_DEV_NODE_PORT
      - RUST_LOG=info
      - RUST_LOG_FORMAT
      - ESPRESSO_DEPLOYER_ALT_CHAIN_PROVIDERS
      - ESPRESSO_DEPLOYER_ALT_MNEMONICS
      - ESPRESSO_SEQUENCER_DEPLOYER_ALT_INDICES
    depends_on:
      - geth
      - sequencer
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fL http://localhost:$ESPRESSO_DEV_NODE_PORT || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  l1data:
  consensus:
  l1keystore:
  seqdata:
  validator-data:
  poster-data:
  config:
  postgres-data:
