version: "3.9"
networks:
  default:
    name: espresso-sequencer
    external: true

services:
  blockscout:
    depends_on:
      - postgres
      - sequencer
    image: blockscout-testnode
    restart: always
    container_name: 'blockscout'
    links:
      - postgres:database
    command:
      - /bin/sh
      - -c
      - |
        bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()"
        node init/install.js postgres 5432
        bin/blockscout start
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - ./blockscout/nitro.env
    environment:
      ETHEREUM_JSONRPC_VARIANT: 'geth'
      ETHEREUM_JSONRPC_HTTP_URL: http://sequencer:8547/
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true"
      DATABASE_URL: postgresql://postgres:@postgres:5432/blockscout
      ECTO_USE_SSL: "false"
    ports:
      - "127.0.0.1:4000:4000"

  postgres:
    image: postgres:13.6
    restart: always
    container_name: 'postgres'
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:7432:5432"

  redis:
    image: redis:6.2.6

  sequencer:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    ports:
      - "127.0.0.1:$L2_PORT_HTTP:8547"
      - "127.0.0.1:$L2_PORT_WS:8548"
    volumes:
      - "seqdata:/home/user/.arbitrum/local/nitro"
      - "config:/config"
    command: --conf.file /config/sequencer_config.json --node.feed.output.enable --node.feed.output.port 9642  --http.api net,web3,eth,txpool,debug --node.seq-coordinator.my-url  ws://sequencer:8548 --graphql.enable --graphql.vhosts * --graphql.corsdomain *
    depends_on:
      - redis

  sequencer_d:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    ports:
      - "127.0.0.1:8847:8547"
      - "127.0.0.1:8848:8548"
    volumes:
      - "seqdata_d:/home/user/.arbitrum/local/nitro"
      - "config:/config"
    command: --conf.file /config/sequencer_config.json --node.seq-coordinator.my-url ws://sequencer_d:8548
    depends_on:
      - redis

  staker-unsafe:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    ports:
      - "127.0.0.1:8047:8547"
      - "127.0.0.1:8048:8548"
    volumes:
      - "unsafestaker-data:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/unsafe_staker_config.json
    depends_on:
      - sequencer
      - redis
      - validation_node

  poster:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    ports:
      - "127.0.0.1:8147:8547"
      - "127.0.0.1:8148:8548"
    volumes:
      - "poster-data:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/poster_config.json
    depends_on:
      - redis

  poster_b:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    ports:
      - "127.0.0.1:9147:8547"
      - "127.0.0.1:9148:8548"
    volumes:
      - "poster-data-b:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/poster_config.json
    depends_on:
      - redis

  poster_c:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    ports:
      - "127.0.0.1:9247:8547"
      - "127.0.0.1:9248:8548"
    volumes:
      - "poster-data-c:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/poster_config.json
    depends_on:
      - redis

  validator:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    ports:
      - "127.0.0.1:$L2_PORT_VALIDATOR_HTTP:8547"
      - "127.0.0.1:$L2_PORT_VALIDATOR_WS:8548"
    volumes:
      - "validator-data:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/validator_config.json --http.port 8547 --http.api net,web3,arb,debug,net,eth --ws.port 8548
    depends_on:
      - sequencer
      - validation_node

  l3node:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    ports:
      - "127.0.0.1:3347:3347"
      - "127.0.0.1:3348:3348"
    volumes:
      - "validator-data:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/l3node_config.json --http.port 3347 --http.api net,web3,arb,debug,eth --ws.port 3348
    depends_on:
      - sequencer
      - validation_node

  validation_node:
    pid: host # allow debugging
    image: nitro-node-dev-testnode
    ports:
      - "127.0.0.1:8949:8549"
    volumes:
      - "config:/config"
    command: --conf.file /config/validation_node_config.json
    entrypoint: /usr/local/bin/nitro-val

  scripts:
    build: scripts/
    volumes:
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    depends_on:
      - redis

  relay:
    pid: host
    image: nitro-node-dev-testnode
    ports:
      - "127.0.0.1:9652:9652"
    entrypoint: bin/relay
    command: --node.feed.output.port 9652 --node.feed.input.url ws://sequencer:9652

  tokenbridge:
    depends_on:
      - sequencer
    pid: host
    build: tokenbridge/
    environment:
      - ARB_URL=http://sequencer:8547
      - ETH_URL=http://demo-l1-network:8545
    volumes:
      - "sdk-data:/workspace"
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  consensus:
  l1keystore:
  seqdata:
  seqdata_b:
  seqdata_c:
  seqdata_d:
  unsafestaker-data:
  validator-data:
  poster-data:
  poster-data-b:
  poster-data-c:
  config:
  postgres-data:
  sdk-data:
