FROM ghcr.io/espressosystems/nitro-espresso-integration/nitro-node-dev:20241124-celestia-pre

COPY ./config /config/
COPY ./l1keystore /l1keystore/

EXPOSE 8547
EXPOSE 8548

ENTRYPOINT ["env", "HOME=/home/user", "/usr/local/bin/nitro", "--validation.wasm.enable-wasmroots-check=false", "--conf.file", "/config/poster_config.json"] 