#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")"

echo "starting nodes"
../test-node.bash --init-force --espresso --latest-espresso-image --validate --detach
sleep 60

# Ignore orphaned container output
# Orphaned containers will be removed at the end of the test
export COMPOSE_IGNORE_ORPHANS=1

good_url=http://espresso-dev-node:41000
bad_url=http://bad-url:41000

docker compose run scripts update-config-value \
    --path /config/poster_config.json \
    --property node.batch-poster.max-empty-batch-delay \
    --value "10h" \

# 1 good url and 1 bad url
# The batcher should not post any batches
echo "modifying poster Hotshot url config to have 1 good url and 1 bad url"
docker compose run scripts update-config-value \
    --path /config/poster_config.json \
    --property node.batch-poster.hotshot-urls \
    --value "$good_url,$bad_url" \
    --isArray true

# update batcher's config
docker compose restart poster

# create L2 traffic
docker compose run scripts send-l2 --ethamount 10 --to user_l2user --times 10 --delay 200

sequencer_inbox=$(docker compose run --entrypoint sh poster -c "jq -r '.[0].rollup.\"sequencer-inbox\"' /config/deployed_chain_info.json | tail -n 1 | tr -d '\r\n'")
echo "sequencer inbox: $sequencer_inbox"
batch_count=$(cast call $sequencer_inbox "batchCount()(uint256)" --rpc-url http://localhost:8545)
echo "batch count: $batch_count"

echo "waiting for 60 seconds for the batcher"
sleep 60

now_batch_count=$(cast call $sequencer_inbox "batchCount()(uint256)" --rpc-url http://localhost:8545)
if [[ $now_batch_count -ne $batch_count ]]; then
    echo "batch count is not the same, the batcher is posting batches"
    exit 1
fi

echo "batcher is not posting batches, which is expected"

# Only 1 good url
# The batcher should fail to start
echo "modifying poster Hotshot url config to only have 1 good url"
docker compose run scripts update-config-value \
    --path /config/poster_config.json \
    --property node.batch-poster.hotshot-urls \
    --value "$good_url" \
    --isArray true

docker compose restart poster

sleep 5

status=$(docker compose ps --status=running --services | grep -w poster || true)
if [[ -z "$status" ]]; then
    echo "Success: poster failed to start as expected."
else
    echo "Error: poster is running but it should have failed to start."
    exit 1
fi


echo "modifying poster Hotshot url config to have 2 good urls"
docker compose run scripts update-config-value \
    --path /config/poster_config.json \
    --property node.batch-poster.hotshot-urls \
    --value "$good_url,$good_url" \
    --isArray true

docker compose restart poster

while true; do
    sleep 10
    now_batch_count=$(cast call $sequencer_inbox "batchCount()(uint256)" --rpc-url http://localhost:8545)
    if [[ $now_batch_count -gt $batch_count ]]; then
        echo "Success: poster is posting batches."
        break
    fi
    echo "waiting for a new batch, batch count: $now_batch_count"
done

docker compose down --remove-orphans
