name: CI
run-name: CI triggered from @${{ github.actor }} of ${{ github.head_ref }}

on:
    workflow_dispatch:
    merge_group:
    pull_request:
    push:
      branches:
        - master
        - integration


jobs:
  build_and_run:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
        restore-keys: ${{ runner.os }}-buildx-

# This is currently broken as L3 node support needs to be fixed
#    - name:  Startup Nitro testnode
#      run: ${{ github.workspace }}/.github/workflows/testnode.bash

