name: CI
run-name: CI triggered from @${{ github.actor }} of ${{ github.head_ref }}

on:
    workflow_dispatch:
    merge_group:
    pull_request:
    push:

# Cancel in-progress jobs except for integration branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'integration/')}}

jobs:
  build_and_run:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host

    - name:  Startup Nitro testnode
      run: ${{ github.workspace }}/.github/workflows/testnode.bash
